// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: proto/vehiculos.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VehiculosServiceClient is the client API for VehiculosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VehiculosServiceClient interface {
	CrearVehiculo(ctx context.Context, in *Vehiculo, opts ...grpc.CallOption) (*VehiculoResponse, error)
	ObtenerVehiculo(ctx context.Context, in *VehiculoId, opts ...grpc.CallOption) (*Vehiculo, error)
	ListarVehiculos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaVehiculos, error)
}

type vehiculosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVehiculosServiceClient(cc grpc.ClientConnInterface) VehiculosServiceClient {
	return &vehiculosServiceClient{cc}
}

func (c *vehiculosServiceClient) CrearVehiculo(ctx context.Context, in *Vehiculo, opts ...grpc.CallOption) (*VehiculoResponse, error) {
	out := new(VehiculoResponse)
	err := c.cc.Invoke(ctx, "/vehiculos.VehiculosService/CrearVehiculo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiculosServiceClient) ObtenerVehiculo(ctx context.Context, in *VehiculoId, opts ...grpc.CallOption) (*Vehiculo, error) {
	out := new(Vehiculo)
	err := c.cc.Invoke(ctx, "/vehiculos.VehiculosService/ObtenerVehiculo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehiculosServiceClient) ListarVehiculos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaVehiculos, error) {
	out := new(ListaVehiculos)
	err := c.cc.Invoke(ctx, "/vehiculos.VehiculosService/ListarVehiculos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VehiculosServiceServer is the server API for VehiculosService service.
// All implementations must embed UnimplementedVehiculosServiceServer
// for forward compatibility
type VehiculosServiceServer interface {
	CrearVehiculo(context.Context, *Vehiculo) (*VehiculoResponse, error)
	ObtenerVehiculo(context.Context, *VehiculoId) (*Vehiculo, error)
	ListarVehiculos(context.Context, *Empty) (*ListaVehiculos, error)
	mustEmbedUnimplementedVehiculosServiceServer()
}

// UnimplementedVehiculosServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVehiculosServiceServer struct {
}

func (UnimplementedVehiculosServiceServer) CrearVehiculo(context.Context, *Vehiculo) (*VehiculoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrearVehiculo not implemented")
}
func (UnimplementedVehiculosServiceServer) ObtenerVehiculo(context.Context, *VehiculoId) (*Vehiculo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerVehiculo not implemented")
}
func (UnimplementedVehiculosServiceServer) ListarVehiculos(context.Context, *Empty) (*ListaVehiculos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListarVehiculos not implemented")
}
func (UnimplementedVehiculosServiceServer) mustEmbedUnimplementedVehiculosServiceServer() {}

// UnsafeVehiculosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VehiculosServiceServer will
// result in compilation errors.
type UnsafeVehiculosServiceServer interface {
	mustEmbedUnimplementedVehiculosServiceServer()
}

func RegisterVehiculosServiceServer(s grpc.ServiceRegistrar, srv VehiculosServiceServer) {
	s.RegisterService(&VehiculosService_ServiceDesc, srv)
}

func _VehiculosService_CrearVehiculo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Vehiculo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiculosServiceServer).CrearVehiculo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vehiculos.VehiculosService/CrearVehiculo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiculosServiceServer).CrearVehiculo(ctx, req.(*Vehiculo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehiculosService_ObtenerVehiculo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VehiculoId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiculosServiceServer).ObtenerVehiculo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vehiculos.VehiculosService/ObtenerVehiculo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiculosServiceServer).ObtenerVehiculo(ctx, req.(*VehiculoId))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehiculosService_ListarVehiculos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehiculosServiceServer).ListarVehiculos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vehiculos.VehiculosService/ListarVehiculos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehiculosServiceServer).ListarVehiculos(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// VehiculosService_ServiceDesc is the grpc.ServiceDesc for VehiculosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VehiculosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vehiculos.VehiculosService",
	HandlerType: (*VehiculosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearVehiculo",
			Handler:    _VehiculosService_CrearVehiculo_Handler,
		},
		{
			MethodName: "ObtenerVehiculo",
			Handler:    _VehiculosService_ObtenerVehiculo_Handler,
		},
		{
			MethodName: "ListarVehiculos",
			Handler:    _VehiculosService_ListarVehiculos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vehiculos.proto",
}
