// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: proto/vehiculos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vehiculos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehiculos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_vehiculos_proto_rawDescGZIP(), []int{0}
}

type Vehiculo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Placa  string `protobuf:"bytes,2,opt,name=placa,proto3" json:"placa,omitempty"`
	Modelo string `protobuf:"bytes,3,opt,name=modelo,proto3" json:"modelo,omitempty"`
	Anio   int32  `protobuf:"varint,4,opt,name=anio,proto3" json:"anio,omitempty"`
	Tipo   string `protobuf:"bytes,5,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Estado string `protobuf:"bytes,6,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Vehiculo) Reset() {
	*x = Vehiculo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vehiculos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vehiculo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehiculo) ProtoMessage() {}

func (x *Vehiculo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehiculos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehiculo.ProtoReflect.Descriptor instead.
func (*Vehiculo) Descriptor() ([]byte, []int) {
	return file_proto_vehiculos_proto_rawDescGZIP(), []int{1}
}

func (x *Vehiculo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehiculo) GetPlaca() string {
	if x != nil {
		return x.Placa
	}
	return ""
}

func (x *Vehiculo) GetModelo() string {
	if x != nil {
		return x.Modelo
	}
	return ""
}

func (x *Vehiculo) GetAnio() int32 {
	if x != nil {
		return x.Anio
	}
	return 0
}

func (x *Vehiculo) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Vehiculo) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type VehiculoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VehiculoId) Reset() {
	*x = VehiculoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vehiculos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehiculoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiculoId) ProtoMessage() {}

func (x *VehiculoId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehiculos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiculoId.ProtoReflect.Descriptor instead.
func (*VehiculoId) Descriptor() ([]byte, []int) {
	return file_proto_vehiculos_proto_rawDescGZIP(), []int{2}
}

func (x *VehiculoId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VehiculoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mensaje string `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *VehiculoResponse) Reset() {
	*x = VehiculoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vehiculos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehiculoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiculoResponse) ProtoMessage() {}

func (x *VehiculoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehiculos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiculoResponse.ProtoReflect.Descriptor instead.
func (*VehiculoResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehiculos_proto_rawDescGZIP(), []int{3}
}

func (x *VehiculoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VehiculoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type ListaVehiculos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehiculos []*Vehiculo `protobuf:"bytes,1,rep,name=vehiculos,proto3" json:"vehiculos,omitempty"`
}

func (x *ListaVehiculos) Reset() {
	*x = ListaVehiculos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_vehiculos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListaVehiculos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaVehiculos) ProtoMessage() {}

func (x *ListaVehiculos) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehiculos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaVehiculos.ProtoReflect.Descriptor instead.
func (*ListaVehiculos) Descriptor() ([]byte, []int) {
	return file_proto_vehiculos_proto_rawDescGZIP(), []int{4}
}

func (x *ListaVehiculos) GetVehiculos() []*Vehiculo {
	if x != nil {
		return x.Vehiculos
	}
	return nil
}

var File_proto_vehiculos_proto protoreflect.FileDescriptor

var file_proto_vehiculos_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c,
	0x6f, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x88, 0x01, 0x0a, 0x08,
	0x56, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x6e, 0x69, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x6e, 0x69, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x70, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x1c, 0x0a, 0x0a, 0x56, 0x65, 0x68, 0x69, 0x63, 0x75,
	0x6c, 0x6f, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x10, 0x56, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x22, 0x43, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x75, 0x6c, 0x6f, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75,
	0x6c, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x52, 0x09, 0x76, 0x65,
	0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x32, 0xda, 0x01, 0x0a, 0x10, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x75, 0x6c, 0x6f, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0d,
	0x43, 0x72, 0x65, 0x61, 0x72, 0x56, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x12, 0x13, 0x2e,
	0x76, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x75,
	0x6c, 0x6f, 0x1a, 0x1b, 0x2e, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x2e, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3f, 0x0a, 0x0f, 0x4f, 0x62, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x75, 0x6c, 0x6f, 0x12, 0x15, 0x2e, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73,
	0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x49, 0x64, 0x1a, 0x13, 0x2e, 0x76, 0x65,
	0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f, 0x73, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x75, 0x6c, 0x6f, 0x73, 0x12, 0x10, 0x2e, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c, 0x6f,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x76, 0x65, 0x68, 0x69, 0x63, 0x75,
	0x6c, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x56, 0x65, 0x68, 0x69, 0x63, 0x75, 0x6c,
	0x6f, 0x73, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x69, 0x6f, 0x2d, 0x65, 0x6e, 0x76, 0x69, 0x6f, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_vehiculos_proto_rawDescOnce sync.Once
	file_proto_vehiculos_proto_rawDescData = file_proto_vehiculos_proto_rawDesc
)

func file_proto_vehiculos_proto_rawDescGZIP() []byte {
	file_proto_vehiculos_proto_rawDescOnce.Do(func() {
		file_proto_vehiculos_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_vehiculos_proto_rawDescData)
	})
	return file_proto_vehiculos_proto_rawDescData
}

var file_proto_vehiculos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_vehiculos_proto_goTypes = []interface{}{
	(*Empty)(nil),            // 0: vehiculos.Empty
	(*Vehiculo)(nil),         // 1: vehiculos.Vehiculo
	(*VehiculoId)(nil),       // 2: vehiculos.VehiculoId
	(*VehiculoResponse)(nil), // 3: vehiculos.VehiculoResponse
	(*ListaVehiculos)(nil),   // 4: vehiculos.ListaVehiculos
}
var file_proto_vehiculos_proto_depIdxs = []int32{
	1, // 0: vehiculos.ListaVehiculos.vehiculos:type_name -> vehiculos.Vehiculo
	1, // 1: vehiculos.VehiculosService.CrearVehiculo:input_type -> vehiculos.Vehiculo
	2, // 2: vehiculos.VehiculosService.ObtenerVehiculo:input_type -> vehiculos.VehiculoId
	0, // 3: vehiculos.VehiculosService.ListarVehiculos:input_type -> vehiculos.Empty
	3, // 4: vehiculos.VehiculosService.CrearVehiculo:output_type -> vehiculos.VehiculoResponse
	1, // 5: vehiculos.VehiculosService.ObtenerVehiculo:output_type -> vehiculos.Vehiculo
	4, // 6: vehiculos.VehiculosService.ListarVehiculos:output_type -> vehiculos.ListaVehiculos
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_vehiculos_proto_init() }
func file_proto_vehiculos_proto_init() {
	if File_proto_vehiculos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_vehiculos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vehiculos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vehiculo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vehiculos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehiculoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vehiculos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehiculoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_vehiculos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListaVehiculos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_vehiculos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vehiculos_proto_goTypes,
		DependencyIndexes: file_proto_vehiculos_proto_depIdxs,
		MessageInfos:      file_proto_vehiculos_proto_msgTypes,
	}.Build()
	File_proto_vehiculos_proto = out.File
	file_proto_vehiculos_proto_rawDesc = nil
	file_proto_vehiculos_proto_goTypes = nil
	file_proto_vehiculos_proto_depIdxs = nil
}
